search functionality complete
leoalano/ascender-automation-practice-test pull request #22
Opened 2022-08-05 01:45 UTC by leoalano

Completei a funcionalidade do search.

2022-08-05 21:41 UTC, JacquesTeixeira commented
Sugestões:
No search_test.robot você pode remover linhas vazias. 39,40,41,42.
No search_resouce você pode remover:
      Resource    ../page_objects/login_page.resource
      Resource    ../page_objects/menu_page.resource
      Resource    ../page_objects/contact_page.resource
      Resource    ../page_objects/footer_page.resource
No search_page.resource você pode remover a linha vazia 7.
O restante está funcionando normalmente, bom trabalho.

2022-08-05 21:53 UTC, JacquesTeixeira commented on tests/search_test.robot
> +
Remover linhas vazias.

2022-08-05 22:14 UTC, JacquesTeixeira requested changes

2022-08-05 22:14 UTC, JacquesTeixeira commented on page_objects/login_page.resource
>  ${EMAIL_CREATE_INPUT}           id=email_create
Descartar: ${EMAIL_CREATE_INPUT}           id=email_create

2022-08-05 22:14 UTC, JacquesTeixeira commented on page_objects/login_page.resource
>  ${EMAIL_INPUT}                  id=email
Descartar: ${EMAIL_INPUT}                  id=email

2022-08-05 22:14 UTC, JacquesTeixeira commented on page_objects/login_page.resource
> -${PASSWORD_EMPTY_VALIDATION}    //li[contains(.,'Password is required.')]
Descartar: ${PASSWORD_EMPTY_VALIDATION}    //li[contains(.,'Password is required.')]

2022-08-05 22:14 UTC, JacquesTeixeira commented on page_objects/login_page.resource
>  ${FORGOT_PASS}                  //a[contains(.,'Forgot your password?')]
Descartar: ${FORGOT_PASS}                  //a[contains(.,'Forgot your password?')]

2022-08-05 22:14 UTC, JacquesTeixeira commented on page_objects/login_page.resource
>  ${RETRIEVE_PASSWORD_BUTTON}     //span[contains(.,'Retrieve Password')]
Descartar: ${RETRIEVE_PASSWORD_BUTTON}     //span[contains(.,'Retrieve Password')]

2022-08-05 22:14 UTC, JacquesTeixeira commented on page_objects/login_page.resource
>  ${RETRIEVED_SUCCESS_MESS}       //p[contains(@class,'alert alert-success')]
Descartar: ${RETRIEVED_SUCCESS_MESS}       //p[contains(@class,'alert alert-success')]

2022-08-05 22:14 UTC, JacquesTeixeira commented on page_objects/login_page.resource
> +${TITLE_PAGE_LOGIN}             Login - My Store
Descartar: ${TITLE_PAGE_LOGIN}             Login - My Store

2022-08-05 22:14 UTC, JacquesTeixeira commented on page_objects/login_page.resource
>  ${TITLE_ACCOUNT}                My account - My Store
Descartar: ${TITLE_ACCOUNT}                My account - My Store

2022-08-05 22:14 UTC, JacquesTeixeira commented on page_objects/login_page.resource
> +${PASSWORD_EMPTY_VALIDATION}    //li[contains(.,'Password is required.')]
Descartar: ${PASSWORD_EMPTY_VALIDATION}    //li[contains(.,'Password is required.')]

2022-08-08 14:38 UTC, leoalano commented on tests/search_test.robot
> +
feito

2022-08-08 18:48 UTC, JacquesTeixeira approved these changes

2022-08-08 18:52 UTC, JacquesTeixeira approved these changes

2022-08-08 18:52 UTC, merged