Refiz o feature/newsletter
leoalano/ascender-automation-practice-test pull request #26
Opened 2022-08-10 00:49 UTC by JacquesTeixeira

Adicionei o newsletter_test.robot e o newsletter.resource,

Acrescentei minhas keywords e variáveis em footer.resource e em footer_page.resource que você criou para a funcionalidade contato.

Não alterei nenhum outro arquivo nesta branch.

2022-08-10 01:21 UTC, leoalano requested changes
Parceido com o outro pull request, unificar as keywords e manter as diferentes variáveis no newsletter_test.robot.

2022-08-10 01:21 UTC, leoalano commented on resources/newsletter.resource
> +I fill with invalid email "${INVALID_EMAIL}"        #TC03-Test with invalid email
Todos estes "I fill with... " no resource podem ser uma só keyword que diz I fill with (aqui qq variável) e colocar as diferentes variáveis no newsletter_test.robot. O "I leave the email empty" pode ser 'I fill with "" 'no test pois aí ele vai preencher com nada pois não há nada entre aspas.

2022-08-10 01:21 UTC, leoalano commented on tests/newsletter_test.robot
> +     When I fill with unregistered email    ${NEW_EMAIL}
Adequar aqui as keywords para unificar tudo com "I fill with ${variável}

2022-08-11 03:18 UTC, JacquesTeixeira commented on resources/newsletter.resource
> +I fill with invalid email "${INVALID_EMAIL}"        #TC03-Test with invalid email
Fiz a unificação das keywords conforme sugerido, e deixei o I fill with "" vazio como sugerido.

2022-08-11 03:18 UTC, JacquesTeixeira commented on tests/newsletter_test.robot
> +     When I fill with unregistered email    ${NEW_EMAIL}
Fiz a unificação das keywords conforme sugerido.

2022-08-11 03:26 UTC, JacquesTeixeira commented
Fiz a unificação das keywords conforme sugerido,
Eu alterei o arquivo newsletter_test.robot, e o newsletter.resource,
Eu criei o newsletter_page.resource que eu não tinha por que estava usando o footer_page.resource(agora não estou mais usando, deixei como era antes).
Eu também não estou usando mais o footer.resource.
Se o projeto passar por um refactor total, talvez possamos discutir o re-mapeamento de algumas vaviáveis, no momento não vejo necessidade.

2022-08-13 18:53 UTC, leoalano approved these changes
ok!

2022-08-13 18:53 UTC, merged