Feature/wishlist
leoalano/ascender-automation-practice-test pull request #30
Opened 2022-08-14 02:36 UTC by JacquesTeixeira

Colegas, o test case 05 estava com um erro e com ajuda do Thomas eu consegui corrigir.

Eu utilizei varias keywords de outros testes, e duas variáveis do
(Resource ../page_objects/catalog_page.resource).

Todos os testes estão ok, analisem e me diga o que vcs acham.

2022-08-14 14:48 UTC, leoalano requested changes
pequena mudança de repetição. basta retirar e estará pronto para merge.

2022-08-14 14:48 UTC, leoalano commented on resources/login.resource
> +Resource    ../page_objects/login_page.resource
Oi Jacques, este resource aqui na linha 4 já existe na linha 2. Pode retirar.

2022-08-15 01:34 UTC, JacquesTeixeira commented on resources/login.resource
> +Resource    ../page_objects/login_page.resource
Tenho quase certeza que fiz um crtl+c, e depois crtl+v, só que acabei deixando no documento errado. Já fiz a correção.

2022-08-15 11:52 UTC, leoalano approved these changes

2022-08-15 11:52 UTC, merged